language: php

php:
  - 5.3
  - 5.4

before_script:
  - composer self-update
  - composer install
  - cp propel-template/build.properties.tpl build.properties && cp propel-template/buildtime-conf.xml.tpl buildtime-conf.xml && cp propel-template/runtime-conf.xml.tpl runtime-conf.xml && cp propel-template/db1.schema.xml.tpl db1.schema.xml  
  - vendor/bin/propel-gen
  - vendor/bin/propel-gen insert-sql


after_success:
  - curl -s http://dev.phpindonesia.net/synchronize

script: vendor/bin/phpunit --coverage-text

