language: php

php:
  - 5.3
  - 5.4

before_script:
  - composer install
  - mysqladmin create phpindonesia
  - mv build.properties.tpl build.properties
  - mv buildtime.xml.tpl buildtime.xml
  - mv connection.xml.tpl connection.xml
  - vendor/bin/propel-gen . diff migrate
  - vendor/bin/propel-gen om
  - vendor/bin/propel-gen convert-conf
  
after_success:
  - curl -s http://dev.phpindonesia.net/synchronize

script: vendor/bin/phpunit --coverage-text

